node ./src/resource_pack/totem/gmgame_totem_page_1.js 
node ./src/resource_pack/totem/gmgame_totem_page_2.js 
node ./src/resource_pack/totem/gmgame_totem_page_3.js 
node ./src/resource_pack/hats/gmgame_hats.js
node ./src/resource_pack/elytra/gmgame_elytra.js
node ./src/resource_pack/drinks/gmgame_drinks.js
node ./src/resource_pack/food/gmgame_food_page_1.js
node ./src/resource_pack/food/gmgame_food_page_2.js

node ./src/spawn_shops/ore/shops_ore.js
node ./src/spawn_shops/item/shops_item.js
node ./src/spawn_shops/tools/shops_tools.js
node ./src/spawn_shops/turtle_helmets/shops_turtle_helmets.js
node ./src/spawn_shops/netherite_helmets/shops_netherite_helmets.js
node ./src/spawn_shops/netherite_chestplates/shops_netherite_chestplates.js
node ./src/spawn_shops/netherite_leggings/shops_netherite_leggings.js
node ./src/spawn_shops/netherite_boots/shops_netherite_boots.js

node ./src/casino/netherite_pickaxe_random/netherite_pickaxe_random.js
node ./src/casino/netherite_hoe_random/netherite_hoe_random.js
node ./src/casino/netherite_axe_random/netherite_axe_random.js
node ./src/casino/netherite_shovel_random/netherite_shovel_random.js
node ./src/casino/bow_crossbow_trident_random/bow_crossbow_trident_random.js
node ./src/casino/all_tools_random/all_tools_random.js
node ./src/casino/money_10_rate_random/money_10_rate_random.js
node ./src/casino/money_25_rate_random/money_25_rate_random.js
node ./src/casino/money_50_rate_random/money_50_rate_random.js
node ./src/casino/money_75_rate_random/money_75_rate_random.js
node ./src/casino/money_100_rate_random/money_100_rate_random.js
node ./src/casino/money_250_rate_random/money_250_rate_random.js
node ./src/casino/money_500_rate_random/money_500_rate_random.js
node ./src/casino/money_750_rate_random/money_750_rate_random.js
node ./src/casino/money_1000_rate_random/money_1000_rate_random.js
node ./src/casino/money_1500_rate_random/money_1500_rate_random.js

node ./src/effect/player_effects_page1.js
node ./src/effect/player_effects_page2.js
node ./src/effect/player_effects_page3.js
node ./src/effect/player_effects_page4.js
node ./src/effect/player_effects_page5.js