# DeluxeMenus 1.14.1-DEV-184 main configuration file
#
# A full wiki on how to use this plugin can be found at:
# https://wiki.helpch.at/clips-plugins/deluxemenus

debug: false
check_updates: true
gui_menus:
  # -------------------- Shops --------------------
  shops_main:
    file: Shops/main_shops.yml
  shops_ore:
    file: Shops/shops_ore.yml
  shops_item:
    file: Shops/shops_item.yml
  shops_equipment:
    file: Shops/shops_equipment.yml
  shops_turtle_helmet:
    file: Shops/shops_turtle_helmet.yml
  shops_netherite_helmet:
    file: Shops/shops_netherite_helmet.yml
  shops_netherite_chestplate:
    file: Shops/shops_netherite_chestplate.yml
  shops_netherite_leggings:
    file: Shops/shops_netherite_leggings.yml
  shops_netherite_boots:
    file: Shops/shops_netherite_boots.yml
  # -------------------- Effects --------------------
  arrow_effect:
    file: Effects/arrow_effect.yml
  # -------------------- Casino --------------------
  casino_netherite_axe:
    file: Casino/casino_netherite_axe.yml